apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-2-e-deployment
  labels:
    app: e-2-e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-2-e
  template:
    metadata:
      labels:
        app: e-2-e
    spec:
      containers:
        - name: e-2-e-container
          image: rutikg/forfun:36311eb322fd24aeb271f327ba59ca61d1842c6f
          ports:
            - containerPort: 3000