apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-2-e-deployment
  labels:
    app: e-2-e
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-2-e
  template:
    metadata:
      labels:
        app: e-2-e
    spec:
      containers:
        - name: e-2-e-container
          image: rutikg/forfun:4fcebdf306130fa31e2e68e9b7ea78f2b893b440
          ports:
            - containerPort: 3000